### ISSUE TITLE
Classy 0.6.3 silently depends on Qt libraries?

### ISSUE THREAD

**Issue by aripollak** [maxmahlke/classy#7]
After upgrading from classy 0.6.1 to 0.6.3, running `classy` or importing it raises an ImportError:

```
% pipx run space-classy
NOTE: running app 'classy' from 'space-classy'
Traceback (most recent call last):
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/bin/classy", line 5, in <module>
    from classy.cli import cli_classy
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/__init__.py", line 7, in <module>
    from .core import Spectrum
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/core.py", line 15, in <module>
    from classy import plotting
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/plotting.py", line 12, in <module>
    from classy import taxonomies
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/taxonomies/__init__.py", line 1, in <module>
    from . import bus, demeo, mahlke, tholen
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/taxonomies/demeo.py", line 12, in <module>
    from classy import preprocessing
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/preprocessing.py", line 6, in <module>
    from classy import gui
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/gui.py", line 8, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/matplotlib/backends/qt_compat.py", line 135, in <module>
    raise ImportError(
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

**Comment by maxmahlke** [comment]
Thanks, version 0.6.4 depends loudly on `pyqtgraph`.

Fyi, I tried adding this dependency as usual using `poetry`. It turns out that packages like `scipy` and `tensorflow` set strict
upper version limits of `python` (mostly `<3.12` at this point), so `poetry` refused to resolve the dependencies for `classy`. It's a mess, I will manually edit the `pyproject.toml` file from now on and see if this makes the dependency nightmare easier to manage.

**Comment by aripollak** [comment]
Thanks, it looks like pyqtgraph has a similar issue though:

```
% pipx run space-classy
NOTE: running app 'classy' from 'space-classy'
Traceback (most recent call last):
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/bin/classy", line 5, in <module>
    from classy.cli import cli_classy
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/__init__.py", line 7, in <module>
    from .core import Spectrum
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/core.py", line 15, in <module>
    from classy import plotting
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/plotting.py", line 12, in <module>
    from classy import taxonomies
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/taxonomies/__init__.py", line 1, in <module>
    from . import bus, demeo, mahlke, tholen
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/taxonomies/demeo.py", line 12, in <module>
    from classy import preprocessing
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/preprocessing.py", line 6, in <module>
    from classy import gui
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/classy/gui.py", line 8, in <module>
    import pyqtgraph as pg
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/ari/.local/pipx/.cache/e893fcbad53a08d/lib/python3.11/site-packages/pyqtgraph/Qt/__init__.py", line 54, in <module>
    raise Exception("PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.")
Exception: PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.
```

**Comment by maxmahlke** [comment]
I added `pyqt5` to the dependencies in version `0.6.5`.
